name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: dir
        run: ls
      - uses: actions/checkout@v1
      - name: dir
        run: ls
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Build static site
        run: yarn install && yarn run build
      - name: dir
        run: ls

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: dir
        run: ls
