name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  AWS_REGION: eu-central-1
  BUCKET_FOLDER_PREVIEW: preview
  BUCKET_FOLDER_PRODUCTION: production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn run test

      - name: Build production
        if: github.ref == 'refs/heads/master'
        run: yarn run build -- --public-url production

      - name: Build preview
        if: github.ref != 'refs/heads/master'
        run: yarn run build -- --public-url preview/${{ github.event.number }}

      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  preview:
    needs: build
    if: github.ref != 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Download dist
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy site to S3 bucket
        if: success()
        run: aws s3 sync ./dist/ s3://${{ secrets.AWS_S3_APP_BUCKET }}/${{ env.BUCKET_FOLDER_PREVIEW }}/${{ github.event.number }} --delete

      - name: Deploy success message
        uses: phulsechinmay/rewritable-pr-comment@v0.2.1
        if: success()
        with:
          message: |
            Deploy preview ready!
            https://${{ secrets.AWS_S3_APP_BUCKET }}.s3-website.${{ env.AWS_REGION }}.amazonaws.com/${{ env.BUCKET_FOLDER_PREVIEW }}/${{ github.event.number }}
            built from ${{ github.sha }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMENT_IDENTIFIER: pr-${{ github.event.number }}

      - name: Deploy failure message
        uses: phulsechinmay/rewritable-pr-comment@v0.2.1
        if: failure()
        with:
          message: |
            Failed to deploy preview
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMENT_IDENTIFIER: pr-${{ github.event.number }}

  deploy:
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Download dist
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy site to S3 bucket
        run: aws s3 sync ./dist/ s3://${{ secrets.AWS_S3_APP_BUCKET }}/${{ env.BUCKET_FOLDER_PRODUCTION }} --delete
